#!/bin/bash

################################################################################
#
#	Test: invalid IP address as input (plain and JSON output formats)
#
################################################################################

result_json="$(cat <<EOF
{
  "error": "invalid IP address (INVALID-IP)"
}
EOF
)"

result_plain="invalid IP address (INVALID-IP)"

diff -w <(./easy-geoip -i INVALID-IP) <(echo "$result_json") || exit 1
diff -w <(./easy-geoip -i INVALID-IP -f json) <(echo "$result_json") || exit 1
diff -w <(./easy-geoip -i INVALID-IP -f plain) <(echo "$result_plain") || exit 1

echo "Passed test: invalid input IP address"

################################################################################
#
#	Test: valid IP address as input (plain and JSON output formats)
#
################################################################################

result_json="$(cat <<EOF
{
  "city": "Mukilteo",
  "continent": {
    "code": "NA",
    "name": "North America"
  },
  "country": {
    "code": "US",
    "name": "United States"
  },
  "ip_address": "1.2.3.4",
  "is_in_european_union": "0",
  "locale_code": "en",
  "metro_code": "819",
  "subdivision1": {
    "code": "WA",
    "name": "Washington"
  },
  "subdivision2": {
    "code": "Unknown",
    "name": "Unknown"
  },
  "time_zone": "America/Los_Angeles"
}
EOF
)"

result_plain="$(cat <<EOF
IP address: 1.2.3.4
Locale code: en
Continent: North America (NA)
Country: United States (US)
Subdivision 1: Washington (WA)
Subdivision 2: Unknown (Unknown)
City: Mukilteo
Metro code: 819
Time zone: America/Los_Angeles
Is in European Union: 0
EOF
)"

diff -w <(./easy-geoip -i 1.2.3.4) <(echo "$result_json") || exit 1
diff -w <(./easy-geoip -i 1.2.3.4 -f json) <(echo "$result_json") || exit 1
diff -w <(./easy-geoip -i 1.2.3.4 -f plain) <(echo "$result_plain") || exit 1

echo "Passed test: input IP address 1.2.3.4"
