#!/bin/bash

################################################################################
#
#	Test: invalid IP address as input (plain and JSON output formats)
#
################################################################################

result_json="$(cat <<EOF
{
  "error": "invalid IP address (INVALID-IP)"
}
EOF
)"

result_plain="invalid IP address (INVALID-IP)"

diff -w <(./easy-geoip -i INVALID-IP) <(echo "$result_json") || exit 1
diff -w <(./easy-geoip -i INVALID-IP -f json) <(echo "$result_json") || exit 1
diff -w <(./easy-geoip -i INVALID-IP -f plain) <(echo "$result_plain") || exit 1

echo "Passed test: invalid input IP address"

################################################################################
#
#	Test: valid IP address as input (plain and JSON output formats)
#
################################################################################

result_json="$(cat <<EOF
{
  "city": "Mountain View",
  "continent": {
    "code": "NA",
    "name": "North America"
  },
  "country": {
    "code": "US",
    "name": "United States"
  },
  "ip_address": "172.217.19.78",
  "is_in_european_union": "0",
  "locale_code": "en",
  "metro_code": "807",
  "subdivision1": {
    "code": "CA",
    "name": "California"
  },
  "subdivision2": {
    "code": "Unknown",
    "name": "Unknown"
  },
  "time_zone": "America/Los_Angeles"
}
EOF
)"

result_plain="$(cat <<EOF
IP address: 172.217.19.78
Locale code: en
Continent: North America (NA)
Country: United States (US)
Subdivision 1: California (CA)
Subdivision 2: Unknown (Unknown)
City: Mountain View
Metro code: 807
Time zone: America/Los_Angeles
Is in European Union: 0
EOF
)"

diff -w <(./easy-geoip -i 172.217.19.78) <(echo "$result_json") || exit 1
diff -w <(./easy-geoip -i 172.217.19.78 -f json) <(echo "$result_json") || exit 1
diff -w <(./easy-geoip -i 172.217.19.78 -f plain) <(echo "$result_plain") || exit 1

echo "Passed test: input IP address 172.217.19.78"
