#!/usr/bin/env bash

################################################################################
#
#	Test: invalid IP address as input (plain and JSON output formats)
#
################################################################################

result_json="$(cat <<EOF
{
  "error": "invalid IP address (INVALID-IP)"
}
EOF
)"

result_plain="invalid IP address (INVALID-IP)"

diff -w <(./easy-geoip -i INVALID-IP) <(echo "$result_json") || exit 1
diff -w <(./easy-geoip -i INVALID-IP -f json) <(echo "$result_json") || exit 1
diff -w <(./easy-geoip -i INVALID-IP -f plain) <(echo "$result_plain") || exit 1

echo "Passed test: invalid input IP address"

################################################################################
#
#	Test: valid IP address as input (plain and JSON output formats)
#
################################################################################

result_json="$(cat <<EOF
{
  "city": "Berlin",
  "continent": {
    "code": "EU",
    "name": "Europe"
  },
  "country": {
    "code": "DE",
    "name": "Germany"
  },
  "ip_address": "160.45.170.10",
  "is_in_european_union": "1",
  "locale_code": "en",
  "metro_code": "Unknown",
  "subdivision1": {
    "code": "BE",
    "name": "Land Berlin"
  },
  "subdivision2": {
    "code": "Unknown",
    "name": "Unknown"
  },
  "time_zone": "Europe/Berlin"
}
EOF
)"

result_plain="$(cat <<EOF
IP address: 160.45.170.10
Locale code: en
Continent: Europe (EU)
Country: Germany (DE)
Subdivision 1: Land Berlin (BE)
Subdivision 2: Unknown (Unknown)
City: Berlin
Metro code: Unknown
Time zone: Europe/Berlin
Is in European Union: 1
EOF
)"

diff -w <(./easy-geoip -i 160.45.170.10) <(echo "$result_json") || exit 1
diff -w <(./easy-geoip -i 160.45.170.10 -f json) <(echo "$result_json") || exit 1
diff -w <(./easy-geoip -i 160.45.170.10 -f plain) <(echo "$result_plain") || exit 1

echo "Passed test: input IP address 160.45.170.10"
